config/routes.rb
Rails.application.routes.draw do

  root to: "public/homes#top"

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get "/" => "homes#top"
    resources :posts, only: [:index, :new, :create, :show, :edit, :update] do
      resources :comments, only: [:create, :destroy]
    end
    resources :users,only:[:index, :show, :edit,:update]
  end

  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  get "users/unsubscribe" => "public/users#unsubscribe", as: "unsubscribe"
  patch "users/withdraw" => "public/users#withdraw" , as: "withdraw"

  scope module: :public do
    resources :posts,only:[:index, :show] do
      resource :favorites, only: [:create, :destroy]
    end
    resources :users,only:[:show, :edit, :update] do
      get  :favorites, on: :collection
    end
  end

  resources :posts do
    resources :comments, only:[:create, :destroy]
  end
   # resources :posts, except: [:index] do
  #    resource :favorites, only: [:create, :destroy]
   # end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @posts = Post.all.order('id DESC').page(params[:page]).per(10)
  end

end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/views/admin/homes/top.html.erb
<div class="container">
  <div class="row">
    <h3 class="col-9">投稿一覧</h3>
    <div class="">
      <%= link_to "新規投稿", new_admin_post_path, class: "btn btn-success" %>
    </div>
  </div>
  <div class="row">
    <table class="col-10 text-center m-3">
      <thead>
        <tr class="table-secondary">
          <td>投稿日時</td>
          <td>件名</td>
        </tr>
      </thead>
      <tbody>
        <% @posts.each do |post| %>
          <tr>
            <td><%= post.updated_at.strftime("%Y/%m/%d %H:%M") %></td>
            <td><%= link_to post.name, admin_post_path(post.id) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="row justify-content-center">
    <%= paginate @posts %>
  </div>
</div>