config/routes.rb
Rails.application.routes.draw do

  root to: "public/homes#top"

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get "/" => "homes#top"
    resources :posts, only: [:index, :new, :create, :show, :edit, :update] do
      resources :comments, only: [:create, :destroy]
    end
    resources :users,only:[:index, :show, :edit,:update]
  end

  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  get "users/unsubscribe" => "public/users#unsubscribe", as: "unsubscribe"
  patch "users/withdraw" => "public/users#withdraw" , as: "withdraw"

  scope module: :public do
    resources :posts,only:[:index, :show] do
      resource :favorites, only: [:create, :destroy]
    end
    resources :users,only:[:show, :edit, :update] do
      get  :favorites, on: :collection
    end
  end

  resources :posts do
    resources :comments, only:[:create, :destroy]
  end
   # resources :posts, except: [:index] do
  #    resource :favorites, only: [:create, :destroy]
   # end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
    scope :active_posts, -> { where(is_active: true) }

    has_one_attached :image
    belongs_to :user, optional: true
    has_many :favorites, dependent: :destroy
    has_many :comments, dependent: :destroy

    belongs_to :tag

    validates :image, presence: true
    validates :is_active, inclusion: { in: [true, false] }
    

    #enum attendance:{join:0, not_join:1}

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to admin_post_path(@post.id)
    else
      @post = Post.new
      render 'new'
    end
  end

  def index
    @posts = Post.all
    @posts = @posts.where('name LIKE ?', "%#{params[:search]}%") if params[:search].present?
    @posts = @posts.where(tag_id: params[:tag_id]) if params[:tag_id].present?
    @posts = @posts.page(params[:page])

    # @posts = Post.all.order('id DESC').page(params[:page]).per(10)
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.page(params[:page])
    @comment = Comment.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post =Post.find(params[:id])
    @post.update(post_params)
    redirect_to admin_post_path(@post.id)
  end

  private

  def post_params
    params.require(:post).permit(:image, :name, :introduction, :is_active, :tag_id)
  end

end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/edit.html.erb
<div class="container">
  <div class="col">
    <h3 class="col-9">投稿編集</h3>
    <%= form_with model: @post, url: admin_post_path do |f| %>
      <p>
        <%= f.label :投稿件名, class: "col-2" %>
        <%= f.text_field :name, class: "col-3" %>
      </p>
      <p>
        <%= f.label :投稿画像, class: "col-2" %>
        <%= f.file_field :image %>
      </p>
      <p>
        <%= f.label :投稿説明, class: "col-2 align-top" %>
        <%= f.text_area :introduction, class: "col-6", style: "height:150px" %>
      </p>
      <p>
        <%= f.label :タグ,class: "col-2" %>
        <%= f.select :tag_id, options_from_collection_for_select(Tag.all, :id, :name),class: "col-6" %>
      </p>
      <p>
        <%= f.label :投稿表示, class: "col-2" %>
        <%= f.radio_button :is_active, true %>表示する
        <%= f.radio_button :is_active, false %>表示しない
      </p>

      <div class="col-2">
        <%=f.submit "変更を保存", class:"btn btn-success"%>
      </div>
  <% end %>
  </div>
</div>

app/views/admin/posts/index.html.erb
<div class="container">
  <div class="row">
    <h3 class="col-8">投稿一覧</h3><%= form_tag admin_posts_path, method: :get, class: 'boards__searchForm' do %>
    <%= select_tag :tag_id, options_from_collection_for_select(Tag.all, :id, :name, params[:tag_id]),
    {prompt: 'タグで絞り込み検索',onchange: 'submit(this.form);'}%>
    <% end %>　
    <div class="">
      <%= link_to "新規投稿", new_admin_post_path, class: "btn btn-success" %>
    </div>
  </div>
  <div class="row">
    <table class="col-11 text-center m-2">
      <thead>
        <tr class="table-secondary">
          <td>投稿日時</td>
          <td>件名</td>
          <td>タグ</td>
        </tr>
      </thead>
      <tbody>
        <% @posts.each do |post| %>
          <tr>
            <td><%= post.updated_at.strftime("%Y/%m/%d %H:%M") %></td>
            <td><%= link_to post.name, admin_post_path(post.id) %></td>
            <td><%=post.tag.name %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="row justify-content-center">
    <%= paginate @posts %>
  </div>
</div>

app/views/admin/posts/new.html.erb
<div class="container">
  <div class="col">
    <h3 class="col-9">新規投稿</h3>
    <%= form_with model: @post, url:admin_posts_path, local:true do |f| %>
      <p>
        <%= f.label :投稿件名,class: "col-2" %>
        <%= f.text_field :name, placeholder: "投稿件名",class: "col-6" %>
      </p>
      <p>
        <%= f.label :画像,class: "col-2" %>
        <%= f.file_field :image, accept: "image/*" %>
      </p>
      <p>
        <%= f.label :投稿説明,class: "col-2 align-top" %>
        <%= f.text_area :introduction, placeholder: "ここに説明を記述します",class: "col-6", style: "height:100px" %>
      </p>
      <p>
        <%= f.label :タグ,class: "col-2" %>
        <%= f.select :tag_id, options_from_collection_for_select(Tag.all, :id, :name), include_blank: "選択してください",class: "col-6" %>
      </p>
      <p>
      <%= f.label :投稿表示,class: "col-2" %>
        <%= f.radio_button :is_active, "true" %>
        <%= f.label :is_active, "表示する" %>
        <%= f.radio_button :is_active, "false" %>
        <%= f.label :is_active, "表示しない" %>
      </p>
      <div class="row justify-content-center">
        <%= f.submit '投稿', class: "btn btn-success" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/posts/show.html.erb
<div class="container">
  <div class="row">
    <h3 class="col-9">投稿詳細</h3>
  </div>

  <div class="mt-3">投稿件名：　<%=@post.name %></div>

  <div class="mt-3">
    投稿画像：　<%=image_tag @post.image,size:"350x250" %>
  </div>

  <div class="mt-3">投稿説明：　<%=@post.introduction %></div>

  <div class="mt-5">タグ名：　<%=@post.tag.name %></div>

  <div class="mt-5">投稿表示：　<% if @post.is_active == true %>
                                  表示する
                                <% else %>
                                  表示しない
                                <% end %>
  </div>

  <div class="comments mt-5">
      <%= form_with model:@comment, url:admin_post_comments_path(@post), local:true do |f| %>
        <%= f.text_area :comment, :size=>"60x3", placeholder: "コメントする" %>
        <%= f.submit "送信する", class: "btn btn-success mb-4" %>
      <% end %>

      <p>コメント件数：<%= @comments.count %></p>
      <% @comments.each do |comment| %>
    	  <div class="comments-index mb-2">
          <%= comment.user.name if comment.user %>
          <%= comment.created_at.strftime('%Y/%m/%d') %><br>
          <div class="d-flex">
            <%= comment.comment %>
            <div class="comment-delete">
              <%= link_to "削除", admin_post_comment_path(comment.post, comment), method: :delete, class: "btn-sm btn-danger ml-4" %>
            </div>
          </div>
        </div>
      <% end %>
      <%= paginate @comments %>
  </div>

  <%=link_to "編集する",edit_admin_post_path(@post),class: "btn btn-success mt-5" %>
</div>