config/routes.rb
Rails.application.routes.draw do

  root to: "public/homes#top"

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get "/" => "homes#top"
    resources :posts, only: [:index, :new, :create, :show, :edit, :update] do
      resources :comments, only: [:create, :destroy]
    end
    resources :users,only:[:index, :show, :edit,:update]
  end

  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  get "users/unsubscribe" => "public/users#unsubscribe", as: "unsubscribe"
  patch "users/withdraw" => "public/users#withdraw" , as: "withdraw"

  scope module: :public do
    resources :posts,only:[:index, :show] do
      resource :favorites, only: [:create, :destroy]
    end
    resources :users,only:[:show, :edit, :update] do
      get  :favorites, on: :collection
    end
  end

  resources :posts do
    resources :comments, only:[:create, :destroy]
  end
   # resources :posts, except: [:index] do
  #    resource :favorites, only: [:create, :destroy]
   # end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user , optional: true
  belongs_to :post

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
    scope :active_posts, -> { where(is_active: true) }

    has_one_attached :image
    belongs_to :user, optional: true
    has_many :favorites, dependent: :destroy
    has_many :comments, dependent: :destroy

    belongs_to :tag

    validates :image, presence: true
    validates :is_active, inclusion: { in: [true, false] }
    

    #enum attendance:{join:0, not_join:1}

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :posts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :is_active, inclusion: { in: [false, true] }

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = 'ゲスト'
    end
  end

end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  
  def create
    post = Post.find(params[:post_id])
    comment = Comment.new(comment_params)
    comment.post_id = post.id
    comment.save
    redirect_to admin_post_path(post)
  end
  
  def destroy
    Comment.find(params[:id]).destroy
    redirect_to admin_post_path(params[:post_id])
  end
  
  private

  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @posts = Post.all.order('id DESC').page(params[:page]).per(10)
  end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to admin_post_path(@post.id)
    else
      @post = Post.new
      render 'new'
    end
  end

  def index
    @posts = Post.all
    @posts = @posts.where('name LIKE ?', "%#{params[:search]}%") if params[:search].present?
    @posts = @posts.where(tag_id: params[:tag_id]) if params[:tag_id].present?
    @posts = @posts.page(params[:page])

    # @posts = Post.all.order('id DESC').page(params[:page]).per(10)
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.page(params[:page])
    @comment = Comment.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post =Post.find(params[:id])
    @post.update(post_params)
    redirect_to admin_post_path(@post.id)
  end

  private

  def post_params
    params.require(:post).permit(:image, :name, :introduction, :is_active, :tag_id)
  end

end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  def after_sign_in_path_for(resource)
    admin_posts_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.all.order('id DESC').page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = '更新しました'
      redirect_to  admin_user_path(@user.id)
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :name_kana, :postal_code, :address, :email, :telephone_number, :is_active)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    post = Post.find(params[:post_id])
    comment = current_user.comments.new(comment_params)
    comment.post_id = post.id
    comment.save
    redirect_to post_path(post)
  end

  def destroy
    Comment.find_by(id: params[:id], post_id: params[:post_id]).destroy
    redirect_to post_path(params[:post_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:comment)
  end

end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kairanban</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm mb-3">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand" href="/"><%= image_tag 'no_image.jpg', size: "100x100" %></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <% if user_signed_in? %>
            <p>
              ようこそ！<br>
              <%= current_user.name %>さん
            </p>
          <% end %>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li class="nav-item p-2">
                  <button type="button" class="btn btn-outline-primary">
                    <%= link_to "マイページ", user_path(current_user.id), class: 'nav-link text-dark' %>
                  </button>
                </li>
                <li class="nav-item p-2">
                  <buttun type="button" class="btn btn-outline-primary">
                    <%= link_to "お知らせ一覧", posts_path, class: 'nav-link text-dark' %>
                  </button>
                </li>
                <li class="nav-item p-2">
                  <buttun type="button" class="btn btn-outline-primary">
                    <%= link_to "お気に入り一覧", favorites_users_path, class: 'nav-link text-dark' %>
                  </button>
                </li>
                <li class="nav-item p-2">
                  <buttun type="button" class="btn btn-outline-primary">
                    <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-dark' %>
                  </buttun>
                </li>
                <li class="mt-4 p-2">
                  <%= form_with url: posts_path, method: :get, local: true do |f| %>
                    <%= f.text_field :search %>
                    <%= hidden_field_tag :tag_id, params[:tag_id] %>
                    <%= f.submit "検索", name: nil %>
                  <% end %>
                </li>
              <% elsif admin_signed_in? %>
                <li class="nav-item p-2">
                  <buttun type="button" class="btn btn-outline-primary">
                    <%= link_to "投稿一覧", admin_posts_path, class: 'nav-link text-light', class: 'nav-link text-dark' %>
                  </buttun>
                </li>
                <li class="nav-item p-2">
                  <buttun type="button" class="btn btn-outline-primary">
                    <%= link_to "会員一覧", admin_users_path, class: 'nav-link text-light', class: 'nav-link text-dark' %>
                  </buttun>
                </li>
                <li class="nav-item p-2">
                  <buttun type="button" class="btn btn-outline-primary">
                    <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' %>
                  </button>
                </li>
                <li class="mt-4 p-2">
                  <%= form_with url: admin_posts_path, method: :get, local: true do |f| %>
                    <%= f.text_field :search %>
                    <%= hidden_field_tag :tag_id, params[:tag_id] %>
                    <%= f.submit "検索", name: nil %>
                  <% end %>
                </li>
              <% else %>
                <li class="nav-item p-2">
                  <buttun type="button" class="btn btn-outline-primary">
                    <%= link_to "お知らせ一覧", posts_path, class: 'nav-link text-dark' %>
                  </button>
                </li>
                <li class="nav-item p-2">
                  <buttun type="button" class="btn btn-outline-primary">
                    <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-dark' %>
                  </buttun>
                </li>
                <li class="nav-item p-2">
                  <buttun type="button" class="btn btn-outline-primary">
                    <%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-dark' %>
                  </buttun>
                </li>
                <li class="nav-item p-2">
                  <buttun type="button" class="btn btn-outline-primary">
                    <%= link_to "お試し", new_user_session_path, class: 'nav-link text-dark' %>
                  </buttun>
                </li>
                <li class="mt-4 p-2">
                  <%= form_with url: posts_path, method: :get, local: true do |f| %>
                    <%= f.text_field :search %>
                    <%= hidden_field_tag :tag_id, params[:tag_id] %>
                    <%= f.submit "検索", name: nil %>
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
    </header>
    <main class="mb-auto">
      <%= yield %>
    </main>
    <footer class="footer">
      <div class="row border-bottom mt-5"></div>
    </footer>
  </body>
</html>